package chap10_exception;

public class ExceptionTest {

	public static void main(String[] args) {
		// 예외 처리
		// 프로그램은 예외가 발생했을때 그 코드에서 멈춘다
		// 코드가 멈추는 것을 막기위해 사용하는 것이 예외처리
		// try/catch
		
		int x = 6;
		int y = 0;
		// try구문안에 있는 변수는 값이 할당되지 않을수도 있기 때문에
		// 미리 초기화
		int result = 0;
		try {
			// 오류/예외가 일어날 가능성이 있는 코드
			int result =x/y;
		} catch(Exception e) {// Exception 클래스의 매개변수를 통해서 오류받아옴
			System.out.println("오류 발생");
		}
		System.out.println("결과 :"+result);

	}

}
